### ISSUE TITLE
'./NutshellEngine' terminated by signal SIGSEGV (Address boundary error)

### ISSUE THREAD

**Issue by Martinfx** [Team-Nutshell/NutshellEngine-WindowModule#2]
Hi,
i don't know where is issue

1. I moved libNutshellEngine-WindowModule.so to engine folder "modules"
2. Run Engine

```
#0  strlen () at /usr/src/lib/libc/amd64/string/strlen.S:45
#1  0x00000008027244e1 in QCoreApplication::arguments() () at /usr/local/lib/qt6/libQt6Core.so.6
#2  0x0000000803cd3429 in ??? () at /usr/local/lib/qt6/plugins/platforms/../..//libQt6XcbQpa.so.6
#3  0x0000000803cd2ef2 in QXcbIntegration::wmClass() const () at /usr/local/lib/qt6/plugins/platforms/../..//libQt6XcbQpa.so.6
#4  0x0000000803ce558c in QXcbWindow::create() () at /usr/local/lib/qt6/plugins/platforms/../..//libQt6XcbQpa.so.6
#5  0x0000000803cd2258 in QXcbIntegration::createPlatformWindow(QWindow*) const () at /usr/local/lib/qt6/plugins/platforms/../..//libQt6XcbQpa.so.6
#6  0x0000000801d7136f in QWindowPrivate::create(bool) () at /usr/local/lib/qt6/libQt6Gui.so.6
#7  0x000000080153db79 in QWidgetPrivate::create() () at /usr/local/lib/qt6/libQt6Widgets.so.6
#8  0x000000080153b6f9 in QWidget::create(unsigned long long, bool, bool) () at /usr/local/lib/qt6/libQt6Widgets.so.6
#9  0x00000008015508ae in QWidgetPrivate::setVisible(bool) () at /usr/local/lib/qt6/libQt6Widgets.so.6
#10 0x0000000801550306 in QWidget::setVisible(bool) () at /usr/local/lib/qt6/libQt6Widgets.so.6
#11 0x000000080095eb62 in QtWindow::open(int, int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) () at ./modules/libNutshellEngine-WindowModule.so
#12 0x0000000800957114 in NtshEngn::WindowModule::openWindow(int, int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) () at ./modules/libNutshellEngine-WindowModule.so
#13 0x00000000002d2e2b in NtshEngn::Core::init() ()
#14 0x00000000002d2ab9 in NtshEngn::Core::launch(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) ()
#15 0x0000000000269a37 in main ()

```

**Comment by Martinfx** [comment]
```
	passSceneManager();

	// Initialize System Modules
	NTSHENGN_POINTER_EXECUTE(m_windowModule, init());
seqfault --->    NTSHENGN_POINTER_EXECUTE(m_windowModule, openWindow(1280, 720, ""));
	NTSHENGN_POINTER_EXECUTE(m_graphicsModule, init());
	NTSHENGN_POINTER_EXECUTE(m_physicsModule, init());
	NTSHENGN_POINTER_EXECUTE(m_audioModule, init());
```

**Comment by ntsh-oni** [comment]
Ok, I found where the issue is. When creating the QApplication, the argc and argv passed should stay alive for the entire lifetime of the application. It should be fixed in the last commit.

**Comment by Martinfx** [comment]
ok, its fixed. Thank you
